title: Reinforcement Learning for Real Life (Rl4RL)
subtitle: A Website for Sharing Rl4RL Projects
description: >- # this means to ignore newlines until "baseurl:"
  The website for the RL4RL project; encouraging researchers to share their applications of Reinforcement Learning to Real Life problems. 
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.rl4rl.com" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: rl4rl_logo.png
disqus_shortname: Philip Osborne  #for comments using disqus
author: Philip Osborne
author_bio: Hello, my name is Philip Osborne. I am a PhD Student of Artificial Intelligence at the Univeristy of Manchester, UK. 
author_email: "philiposbornedata@gmail.com"
author_location: Manchester/London UK
author_website_url: "https://philiposbornedata.com"
# social links
twitter_username: yourusername
github_username:  yourusername
facebook_username: yourusername
linkedin_username: yourusername
behance_username: yourusername
instagram_username: yourusername
medium_username: yourusername 
telegram_username: yourusername
dribbble_username: yourusername 
flickr_username: yourusername
