title: Reinforcement Learning for Real Life
subtitle: Homepage of the RL4RL Project
description: >- # this means to ignore newlines until "baseurl:"
  The website for the RL4RL project; encouraging state of the art applications of Reinforcement Learning to Real Life problems. 
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.rl4rl.com" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: rl4rl_logo.png
post_author_logo_1: profile.png

disqus_shortname: Philip Osborne  #for comments using disqus
author: Philip Osborne
author_bio: Hello, my name is Philip Osborne. I am a PhD Student of Artificial Intelligence at the Univeristy of Manchester, UK. 
author_email: "philiposbornedata@gmail.com"
author_location: Manchester/London UK
author_website_url: "https://philiposbornedata.com"
# social links
twitter_username: DataOsborne
github_username:  osbornep
#facebook_username: yourusername
linkedin_username: philip-osborne-1052a183
#behance_username: yourusername
instagram_username: osbornep1
medium_username: sterlingosborne 
#telegram_username: yourusername
#dribbble_username: yourusername 
#flickr_username: yourusername
